import './globals.css';
import type { Metadata } from 'next';
import { setBrowserTabTitle } from '@/core/utils';

export const metadata: Metadata = {
  title: setBrowserTabTitle('Chat Web'),
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return <>{children}</>;
};

export default RootLayout;
